# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040ae44d8c71e42c52035fdb4fd17ea60118fc05ba1b71e115e0278ea1ec764e12292840eebb8731a6fbd3b26404aa9ba3c966914572330ec711dc0dc9ddaa29

test:
  secret_key_base: a8a8dfb9e569fc4eff91d9e866c023847a2f5ec6c535523f9212eaf003a44fdadf8911098a43175992e6886876fcbaac8f2d9cee5d470576d40318cc7b6d29ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
